from staze import Error


class AuthError(Error):
    pass